contao:
  backend:
    attributes:
      app-name: 'My App'
      app-version: 1.2.3
    badge_title: develop
  image:
    sizes:
      topnews:
        width: 1920
        height: 1080
        resize_mode: crop
        densities: 2x, 3x
        css_class: max-w-full h-auto w-full block
        formats:
          jpg: [webp, jpg]
          webp: [webp, jpg]
          png: [webp, png]
        items:
            -
              media: '(max-width: 768px)'
              width: 800
              height: 600
              resize_mode: crop
              densities: 2x, 3x
