on:
  push:
    branches:
      - main
name: 🇸🇱 Deploy steelers.de (Production) 🇸🇱
jobs:
  web-deploy:
    name: 🇸🇱 Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: 🏗 build css and js
        uses: actions/setup-node@v3
        env:
          COMPOSE_TLS_VERSION: TLSv1_2
        with:
          node-version: 24
      - run: cd assets && npm ci
      - run: cd assets && npm run build

      - name: 🚀 Deploy to prod
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dep: deploy stage=prod
          deployer-version: "7.5.12"
